---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      become: true
      apt:
        wait: 600 seconds
      # Your code here
    - name: "upgrade packages."
      become: true
      apt:
        upgrade: "yes"
    - name: "install dependencies."
      become: true
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes
    - name: "install pm2"
      become: true
      npm:
        name: pm2
        global: yes
        production: yes
        state: present
  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    - TYPEORM_ENTITIES: "./modules/domain/**/*.entity{.ts,.js}"
    - TYPEORM_HOST: webserver
    - TYPEORM_PORT: 5532
    - TYPEORM_USERNAME: webserver
    - TYPEORM_PASSWORD: 12345678
    - TYPEORM_DATABASE: webserver
    # Add more env vars here

  roles:
    # Your code here