---
  # - name: "update apt packages."
  #   become: true
  #   apt:
  #     update_cache: yes
  - name: "Update apt-get repo and cache"
    become: true
    apt: 
      update_cache=yes 
      force_apt_get=yes 
      cache_valid_time=3600

  - name: "install nodejs and npm"
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install n"
    become: true
    npm:
      name: n
      global: yes
      production: yes

  - name: "install nodejs 13.8.0"
    become: true
    shell: n 13.8.0

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present